// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Transfer struct {
	SenderID    string
	ID          string
	RecipientID string
	AmountMinor int64
	Notes       string
	CreatedAt   time.Time
}

type User struct {
	ID             string
	Email          string
	PasswordHash   string
	LastActivityAt sql.NullTime
}

type Wallet struct {
	UserID       string
	BalanceMinor int64
}
