// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash)
VALUES (?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id, balance_minor)
VALUES (?, ?)
`

type CreateWalletParams struct {
	UserID       string
	BalanceMinor int64
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) error {
	_, err := q.db.ExecContext(ctx, createWallet, arg.UserID, arg.BalanceMinor)
	return err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT email
FROM users
WHERE id = ?
`

func (q *Queries) GetEmailByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmailByID, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const getLastActivity = `-- name: GetLastActivity :one
SELECT last_activity_at
FROM users
WHERE id = ?
`

func (q *Queries) GetLastActivity(ctx context.Context, id string) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getLastActivity, id)
	var last_activity_at sql.NullTime
	err := row.Scan(&last_activity_at)
	return last_activity_at, err
}

const getTransferBySenderAndID = `-- name: GetTransferBySenderAndID :one
SELECT
  sender_id,
  id,
  recipient_id,
  amount_minor,
  notes,
  created_at
FROM transfers
WHERE sender_id = ? AND id = ?
FOR UPDATE
`

type GetTransferBySenderAndIDParams struct {
	SenderID string
	ID       string
}

func (q *Queries) GetTransferBySenderAndID(ctx context.Context, arg GetTransferBySenderAndIDParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransferBySenderAndID, arg.SenderID, arg.ID)
	var i Transfer
	err := row.Scan(
		&i.SenderID,
		&i.ID,
		&i.RecipientID,
		&i.AmountMinor,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, last_activity_at
FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.LastActivityAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT user_id, balance_minor
FROM wallets
WHERE user_id = ?
`

func (q *Queries) GetWallet(ctx context.Context, userID string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.BalanceMinor)
	return i, err
}

const insertTransfer = `-- name: InsertTransfer :exec
INSERT INTO transfers (
  sender_id,
  id,
  recipient_id,
  amount_minor,
  notes,
  created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTransferParams struct {
	SenderID    string
	ID          string
	RecipientID string
	AmountMinor int64
	Notes       string
	CreatedAt   time.Time
}

func (q *Queries) InsertTransfer(ctx context.Context, arg InsertTransferParams) error {
	_, err := q.db.ExecContext(ctx, insertTransfer,
		arg.SenderID,
		arg.ID,
		arg.RecipientID,
		arg.AmountMinor,
		arg.Notes,
		arg.CreatedAt,
	)
	return err
}

const listTransfersForUser = `-- name: ListTransfersForUser :many
SELECT
  t.sender_id,
  t.id,
  t.recipient_id,
  t.amount_minor,
  t.notes,
  t.created_at,
  sender.email AS sender_email,
  recipient.email AS recipient_email
FROM transfers t
JOIN users sender ON sender.id = t.sender_id
JOIN users recipient ON recipient.id = t.recipient_id
WHERE t.sender_id = ? OR t.recipient_id = ?
ORDER BY t.created_at ASC, t.id ASC
`

type ListTransfersForUserParams struct {
	UserID string
}

type ListTransfersForUserRow struct {
	SenderID       string
	ID             string
	RecipientID    string
	AmountMinor    int64
	Notes          string
	CreatedAt      time.Time
	SenderEmail    string
	RecipientEmail string
}

func (q *Queries) ListTransfersForUser(ctx context.Context, arg ListTransfersForUserParams) ([]ListTransfersForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransfersForUser, arg.UserID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransfersForUserRow
	for rows.Next() {
		var i ListTransfersForUserRow
		if err := rows.Scan(
			&i.SenderID,
			&i.ID,
			&i.RecipientID,
			&i.AmountMinor,
			&i.Notes,
			&i.CreatedAt,
			&i.SenderEmail,
			&i.RecipientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWallet = `-- name: LockWallet :one
SELECT user_id, balance_minor
FROM wallets
WHERE user_id = ?
FOR UPDATE
`

func (q *Queries) LockWallet(ctx context.Context, userID string) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, lockWallet, userID)
	var i Wallet
	err := row.Scan(&i.UserID, &i.BalanceMinor)
	return i, err
}

const setBalance = `-- name: SetBalance :exec
UPDATE wallets
SET balance_minor = ?
WHERE user_id = ?
`

type SetBalanceParams struct {
	BalanceMinor int64
	UserID       string
}

func (q *Queries) SetBalance(ctx context.Context, arg SetBalanceParams) error {
	_, err := q.db.ExecContext(ctx, setBalance, arg.BalanceMinor, arg.UserID)
	return err
}

const setLastActivity = `-- name: SetLastActivity :exec
UPDATE users
SET last_activity_at = ?
WHERE id = ?
`

type SetLastActivityParams struct {
	LastActivityAt sql.NullTime
	ID             string
}

func (q *Queries) SetLastActivity(ctx context.Context, arg SetLastActivityParams) error {
	_, err := q.db.ExecContext(ctx, setLastActivity, arg.LastActivityAt, arg.ID)
	return err
}
